### ISSUE TITLE
File IndexError: list index out of range in start, length = object_indexes[object_id]

### ISSUE THREAD

**Issue by alice-cool** [Zhiquan-Wen/D-VQA#7]
Original Traceback (most recent call last):
  File "/home/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/byd/D-VQA-master/LXMERT/src/dataset_vqacp_lxmert.py", line 218, in __getitem__
    feature = self.m.fetchone(colletion_id=true_feature_id, object_id=1)
  File "/home/byd/D-VQA-master/LXMERT/mio/reader.py", line 55, in fetchone
    return self._fetch(colletion_id, object_id)
  File "/home/byd/D-VQA-master/LXMERT/mio/reader.py", line 75, in _fetch
    start, length = object_indexes[object_id]
IndexError: list index out of range

**Comment by alice-cool** [comment]
学者您好，我在其他两个基准都能跑通，在lxmert 就报错mio 的问题。不知道是哪里出错了

**Comment by alice-cool** [comment]
BertAdam Total Iters: 136940
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/home/byd/D-VQA-master/LXMERT/src/tasks/main.py", line 271, in <module>
    vqa.train(vqa.train_loader, vqa.val_loader)
  File "/home/byd/D-VQA-master/LXMERT/src/tasks/main.py", line 164, in train
    for i, (feats, boxes, sent, target, ques_id) in tqdm(enumerate(train_loader)):
  File "/home/anaconda3/envs/pytorch/lib/python3.9/site-packages/tqdm/std.py", line 1180, in __iter__
    for obj in iterable:
  File "/home/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/home/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/home/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/byd/D-VQA-master/LXMERT/src/dataset_vqacp_lxmert.py", line 218, in __getitem__
    feature = self.m.fetchone(colletion_id=true_feature_id, object_id=1)
  File "/home/byd/D-VQA-master/LXMERT/mio/reader.py", line 55, in fetchone
    return self._fetch(colletion_id, object_id)
  File "/home/byd/D-VQA-master/LXMERT/mio/reader.py", line 75, in _fetch
    start, length = object_indexes[object_id]
IndexError: list index out of range

**Comment by LemonQC** [comment]
How can you fix it?
